version: "3.9"

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
    - 80:80
    volumes:
    - octoprint:/octoprint
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - octoprint
volumes:
  octoprint: